name: Update Packages

on:
  schedule:
    - cron: '37 3 * * *'
  workflow_dispatch:

jobs:
  update:
    uses: Cratis/Workflows/.github/workflows/update-packages.yml@main
    secrets:
      PAT_WORKFLOWS: ${{ secrets.PAT_WORKFLOWS }}
